application: www-dindinet-site
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /assets/img
  static_dir: static/assets/img

- url: /assets/css
  static_dir: static/assets/css

- url: /assets/js
  static_dir: static/assets/js